# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CSLobJackpot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CSLobJackpot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CSGameDef_pb2 as CSGameDef__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x43SLobJackpot.proto\x12\x02pb\x1a\x0f\x43SGameDef.proto\"1\n\rLobJackPotREQ\x12\r\n\x05\x62lind\x18\x01 \x01(\x03\x12\x11\n\tgame_type\x18\x02 \x01(\x05\"H\n\rLobJackPotRSP\x12\r\n\x05\x62lind\x18\x01 \x01(\x03\x12\x15\n\rjackpot_chips\x18\x02 \x01(\x03\x12\x11\n\tgame_type\x18\x03 \x01(\x05\"d\n\x12LobJackPotPrizeBRC\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\r\n\x05\x63\x61rds\x18\x02 \x03(\x05\x12\r\n\x05prize\x18\x03 \x01(\x03\x12\x15\n\rjackpot_chips\x18\x04 \x01(\x03\x12\x0c\n\x04type\x18\x05 \x01(\x05\"7\n\x13LobJackPotConfigREQ\x12\r\n\x05\x62lind\x18\x01 \x01(\x03\x12\x11\n\tgame_type\x18\x02 \x01(\x05\"E\n\x13LobJackPotConfigRSP\x12\r\n\x05\x62lind\x18\x01 \x01(\x03\x12\x0c\n\x04rate\x18\x02 \x03(\x05\x12\x11\n\tgame_type\x18\x03 \x01(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CSLobJackpot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOBJACKPOTREQ']._serialized_start=43
  _globals['_LOBJACKPOTREQ']._serialized_end=92
  _globals['_LOBJACKPOTRSP']._serialized_start=94
  _globals['_LOBJACKPOTRSP']._serialized_end=166
  _globals['_LOBJACKPOTPRIZEBRC']._serialized_start=168
  _globals['_LOBJACKPOTPRIZEBRC']._serialized_end=268
  _globals['_LOBJACKPOTCONFIGREQ']._serialized_start=270
  _globals['_LOBJACKPOTCONFIGREQ']._serialized_end=325
  _globals['_LOBJACKPOTCONFIGRSP']._serialized_start=327
  _globals['_LOBJACKPOTCONFIGRSP']._serialized_end=396
# @@protoc_insertion_point(module_scope)
