syntax = "proto2";
package pb;

import "CSGameDef.proto";

message ActionNotifyBRC
{
    optional int32 seatid = 1;
    optional int64 call_need_chips = 2; //跟注需要的筹码，有可能比手上的筹码多
    optional int64 min_chipin = 3; //加注需要的最小筹码量，有可能比手上的筹码多，遇到无效加注的情况，玩家不能raise，min_chipin为0
    optional int64 max_chipin = 4; //可以下的最大筹码量
    optional int32 pre_action_result = 5; //0 没有设置预行动，1 预行动被重置，2 执行预行动
    optional int32 think_time = 6; //sng本局还能思考的时间长度
}

//回合开始
message RoundStartBRC
{
    optional int32 stage = 1;
    repeated int32 board = 2; //公共牌
}

//回合结束
message RoundOverBRC
{
    repeated int64 pool = 1; //奖池
}

//发手牌
message HandCardRSP
{
    optional int32 card1 = 1;
    optional int32 card2 = 2;
    optional int32 card3 = 3;
    optional int32 card4 = 4;
}

message PreActionREQ //预行动请求
{
    optional int32 type = 1; //0:取消预行动 1:check or fold 2:call current 3:call any
    optional int64 chips = 2; // call current需要传chips
}

message PreActionRSP //预行动返回
{
    optional int32 code = 1;
    optional int32 type = 2; //0:取消预行动 1:check or fold 2:call current 3:call any
    optional int64 chips = 3; // call current需要传chips
}

message PreActionResetRSP //预行动被重置
{
}

message WinningInfo
{
    optional int32 seatid = 1;  //座位id
    optional int32 poolid = 2;  //奖池id
    optional int64 chips = 3;  //奖励筹码,包含本金,已去除fee
    optional int32 type = 4; //赢牌类型
    optional int64 uid = 6;
    optional int64 jackpot_fee = 7;
}

message WinningProfit
{
    optional int32 seatid = 1;
    optional int64 chips = 2; //PROFIT额
    optional int32 fire_power = 3[default = 0]; // 胜利者获得的火力值
    optional int32 win_exp = 4[default = 0]; // 胜利者获得的经验
    optional int32 bond_add = 5[default = 0]; // 胜利者获得的好感度
    optional int64 uid = 6;
}

message WinnerRSP
{
    repeated WinningInfo winner 	= 1;
    repeated WinningProfit profit 	= 2;
}

message ShowHandInfo
{
    optional int32 seatid = 1;  //座位id
    optional int32 card1 = 2;
    optional int32 card2 = 3;
    optional int32 card3 = 4;
    optional int32 card4 = 5;
}

message ShowHandRSP
{
    repeated ShowHandInfo info = 1;
}

//开局信息，参与牌局的座位与筹码
message StartInfo
{
    optional int32 seatid = 1;
    optional int64 chips = 2;
}

message DealerInfoRSP
{
    optional int32 dealer = 1;
    optional int32 small_blind = 2;
    optional int32 big_blind = 3;
    repeated StartInfo start_info = 4;
    optional string gameid = 5;
}

message TableGameOverRSP
{
    optional int32 type = 1; // 1 房间时间到   2 服务器停服   3 不够2人开局  4 热更解散旧房间
}

message ShowMyCardREQ
{
    optional string gameid = 1;
    optional int32 pos = 2; // 操作的手牌位置(1,2,3,4), 1表示左数第一张牌, 2表示左数第二张牌, ...
    optional int32 flag = 3; // 1:展示  0或其他值取消展示
}
message ShowMyCardRSP
{
    optional int32 code = 1;
    optional string gameid = 2;
    optional int32 pos = 3; // 操作的手牌位置(1,2,3,4), 1表示左数第一张牌, 2表示左数第二张牌, ...
    optional int32 flag = 4; // 1:展示  0或其他值取消展示
}

message ShowMyCardBRC
{
    optional string gameid = 1;
    repeated ShowMyCardInfo info = 2;
}

//筹码从桌子返回到手里
message ChipsBackBRC
{
    optional int32 seatid = 1;
    optional int64 chips = 2;
}

//取消等待大盲设置(已废弃)
message CancelWaitBlindREQ
{
    optional bool wait_blind = 1[default = true]; //poker设置等待大盲 true: wait bb, false pay bb
}

message CancelWaitBlindBRC
{
    optional int32 seatid = 1;
    optional bool wait_blind = 2;
}

message SetWaitBlindTypeREQ
{
    optional bool wait_blind = 1; // true:等到大盲位再加入 false:支付大盲立刻加入
}
message SetWaitBlindTypeRSP
{
    optional int32 code = 1;
    optional int32 wait_blind_type = 2; // 是否需要等待大盲位再加入牌局 0:支付大盲立刻加入 1:等到大盲位再加入 2:不等待(不需要支付大盲)
}

message RebyREQ
{
    optional bool is_reby = 1; //reby
    optional int64 chips = 2;
}

message RebyBRC
{
    optional int32 code = 1;
    optional int32 seatid = 2;
    optional int64 chips = 3;
    optional string type = 4; // 补码类型, 取值: reby/auto_reby/topup/allinfold_topup
}

message NoticeRebyRSP
{
    optional int32 type = 1; // 1没有chips
    optional int32 seatid = 2;
    optional int32 reby_left_time = 3; //等待reby剩余时间,单位:秒
}

message SetRebyREQ
{
    optional int64 reby_chips = 1;  // 设置reby的值
}

message SetRebyRSP
{
    optional int32 code = 1;
    optional int64 reby_chips = 2;  //reby的值
}

//行动请求
message ActionREQ
{
    optional int32 action_type = 1;
    optional int64 chips = 2;
}

message ActionRSP
{
    optional int32 code = 1;
}

//行动广播
message ActionBRC
{
    optional int32 seatid = 1;
    optional int32 action_type = 2;
    optional int64 chips = 3;
    optional int64 hand_chips = 4;  //BET后剩余筹码
}

message GetCardsREQ
{
}

message GetCardsRSP
{
    repeated int32 board_cards = 1;
    optional int32 card1 = 2;
    optional int32 card2 = 3;
}

message AnteInfo
{
    optional int32 seatid = 1;
    optional int64 ante = 2;
}

message AnteBRC
{
    repeated AnteInfo info = 1;
}

message PlayerHands
{
    optional UserBrief brief = 1;
    repeated uint32 cards = 2;
    optional int64 profit = 3;
    optional int32 hand_type = 4; // 牌型,取值参考game_def.md中的holdem_hand_type
    optional bool is_fold = 5;  // true为弃牌，false则不是弃牌
    repeated int32 show_card_info = 6; // 玩家设置的show牌信息 show_card_info[0]表示左起第一张牌是否show，0表示不show，1表示show
}

message HandsInfo
{
    optional int32 id = 1; //手牌序列号,从1开始累加
    repeated PlayerHands hands = 2;
    repeated uint32 board = 3;
    optional string gameid = 4;
}

//poker手牌列表
message GetHandsListREQ
{
    optional int32 id = 1; //手牌序列号,从1开始累加,0表示获取最新的手牌
}

message GetHandsListRSP
{
    optional int32 code = 1;
    optional HandsInfo info = 2;
}

// 回合开始的动画播放结束后通知服务端
message RoundStartDisplayFinishREQ
{
    optional string gameid = 1;
    optional int32 stage = 2; // 1:preflop, 2:flop, 3:turn, 4:river
}
message RoundStartDisplayFinishRSP
{
    optional int32 code = 1;
}

// MTT与SNG盲注信息通知
message BlindStatusBRC
{
    optional int32 blind_level = 1; // 当前级别
    optional int32 upblind_time = 2; // 本级别剩余时间，单位:秒
}

//停止涨盲
// message BlindStopBRC
// {
//     optional int32 type = 1; // 1 休息  2 addon
// }
