syntax = "proto2";
package pb;

import "CSGameDef.proto";

message RoleListREQ
{
}

message RoleListRSP
{
    optional int32 send_gift_cnt = 1; // 每日已送礼次数
    repeated RoleInfo role_list = 2; // 角色列表
    optional int32 using_role_id = 3; // 当前使用的角色id
    repeated int32 owned_skin_ids = 4; // 已拥有的皮肤id列表
}

// 角色信息变化通知
// message RoleChangeRSP
// {
//     optional RoleInfo role_info = 1; // 角色信息
// }

// 角色标星或取消标星
message RoleSetStarREQ
{
    optional int32 role_id = 1;
    optional bool is_star = 2; // 是否标星, true=标星，false=取消标星
}

message RoleSetStarRSP
{
    optional int32 code = 1;
    optional int32 role_id = 2;
    optional bool is_star = 3; // 是否标星, true=标星，false=取消标星
}

// 切换角色
message SwitchRoleREQ
{
    optional int32 new_role_id = 1; // 新角色配置id
}
message SwitchRoleRSP
{
    optional int32 code = 1;
    optional int32 new_role_id = 2;
}

// 切换角皮肤
message SwitchRoleSkinREQ
{
    optional int32 role_id = 1;
    optional int32 new_skin_id = 2; // 新皮肤id
}
message SwitchRoleSkinRSP
{
    optional int32 code = 1;
    optional int32 role_id = 2;
    optional int32 new_skin_id = 3;
}

// 给角色送礼
message RoleGiftREQ
{
    optional int32 role_id = 1;
    optional string item_uniq_id = 2; // 礼物道具的唯一id
}

message RoleGiftRSP
{
    optional int32 code = 1;
    optional int32 send_gift_cnt = 2; // 今日已送礼次数
    optional int32 role_id = 3; // 角色id
    optional string item_uniq_id = 4; // 礼物道具的唯一id
    optional RoleBondChangeRSP bond_change_rsp = 5; // 好感度变化
}

// 角色好感度变化通知
message RoleBondChangeRSP
{
    optional int32 role_id = 1;
    optional int32 level = 2; // 角色当前等级
    optional int32 bond_exp = 3; // 角色当前的好感度
    optional int32 bond_inc = 4; // 好感度变化值
}

// 角色觉醒请求
message RoleAwakenREQ
{
    optional int32 role_id = 1;
}
message RoleAwakenRSP
{
    optional int32 code = 1;
    optional int32 role_id = 2;
}

// 角色解锁通知
message RoleUnlockRSP
{
    optional RoleInfo role_info = 1; // 解锁的角色
}
// 皮肤解锁通知
message SkinUnlockRSP
{
    optional int32 skin_id = 1; // 解锁的皮肤id
}

message EditFavoriteRoleREQ
{
    optional int32 skin_id = 1; // 角色皮肤id
    optional bool is_favorite = 2; // 是否设置为喜爱角色, true:收藏，false:取消收藏
}

message EditFavoriteRoleRSP
{
    optional int32 code = 1;
    optional int32 skin_id = 2; // 角色皮肤id
    optional bool is_favorite = 3; // 是否设置为喜爱角色
}

message SkinGameDetailItem
{
    optional int32 skin_id = 1;
    optional int32 game_cnt = 2; // 使用该皮肤进行游戏的次数
}
message GetSkinGameDetailREQ
{
}
message GetSkinGameDetailRSP
{
    optional int32 code = 1;
    repeated SkinGameDetailItem skin_game_details = 2;
}