syntax = "proto2";
package pb;

message ColorGameBet
{
    optional int32 id = 1; // 101黄, 102灰, 103紫, 104蓝, 105红, 106绿
	optional int64 value = 2; // 总下注额
}

message ColorGameProfit
{
    optional int32 id = 1; // 101黄, 102灰, 103紫, 104蓝, 105红, 106绿
	optional int64 profit = 2; // 包含本金，未中奖时为零
}

message ColorGameActionREQ
{
	optional int32 from_game_type = 1; // 在什么地方玩color game；0大厅，非0则是具体玩法
	repeated ColorGameBet bets = 2;
	optional int32 lvl = 3; // 买入等级
}

message ColorGameActionRSP
{
    optional int32 code = 1;
	repeated ColorGameBet bets = 2; // 下注
	repeated ColorGameProfit profits = 3; // 结算
	repeated int32 ids = 4; // 结果id列表，颜色列表
}
message GetColorGameConfREQ
{

}
message GetColorGameConfRSP
{
    optional int32 code = 1;
	optional string conf = 2;//json格式
}
message PushGiftREQ
{
	optional int32 from_game_type = 1; // 在什么地方玩color game；0大厅，非0则是具体玩法
	optional int32 lvl = 2; // 买入等级
	optional int32 game_type = 3;//游戏类型 30030101 color game
}
//推送礼包
message PushGiftRSP
{
	optional int32 code = 1;
	optional int32 gift_id = 2;//推送礼包id
	optional int32 game_type = 3;
}
//小游戏获取历史记录
message GetSideGameHisRecordREQ
{
	optional int32 game_type = 1;
}
// chips下注筹码 profit:纯利润(负数则是输)
// 30030101 - bet_data:[[{chips: 0,profit: 0,id:105}],],result:[[106,105],]
// 30080101 - bet_data:[{chips: 0,profit: 0,num: 10},],result:[[{export_id:1, rate:11},...],]
message GetSideGameHisRecordRSP
{
	optional int32 code = 1;
	optional int32 game_type = 2;
	optional string bet_data = 3;//    
	optional string result = 4;
}

// 获取小游戏配置
message GetSideGameConfREQ
{
    optional int32 game_type = 1; // 玩法类型
}
// tpl_conf: 玩法配置, 例如: tpl_color_game.lua中的P
// 30030101 - conf:{tpl_conf:{}}
// 30080101 - conf:{tpl_conf:{},balls:[1,2,3,5,10],export:[{export_id:1, rate:11},...]}
message GetSideGameConfRSP
{
    optional int32 code = 1;
    optional int32 game_type = 2;
    optional string conf = 3;//json格式
}

message PinballBallInfo
{
    optional int32 ball_id = 1;
    optional int32 export_id = 2; // 出口ID, 从左往右依次是1~9
    optional int64 reward = 3; // 奖励金额,连本带利
    optional int64 profit = 4; // 盈利, 即:奖励金额-下注金额, 可能为负数
}

message PinballActionResult
{
    optional int32 start_time = 1; // 开始发射小球的时间戳
    repeated PinballBallInfo balls = 2; // 小球信息列表
    optional int32 ball_fire_interval = 3; // 小球发射间隔，单位毫秒
    optional int32 per_ball_move_time = 4; // 每个小球移动时间，单位毫秒
    optional int32 from_game_type = 5; // 在什么地方玩color game；0大厅，非0则是具体玩法
}

message PinballActionREQ
{
    optional int32 from_game_type = 1; // 在什么地方玩color game；0大厅，非0则是具体玩法
    optional int32 lvl = 2; // 买入等级
    optional int64 per_bet = 3; // 每个球的下注金额
    optional int32 ball_num = 4; // 球的数量
}

message PinballActionRSP
{
    optional int32 code = 1;
    optional PinballActionResult action_result = 2;
