# Interceptor configuration
from pathlib import Path

# ── Real game server ─────────────────────────────────────────────────────────
# Fill in the actual hostname from your mitmproxy capture.
SERVER_HOST      = "zga-entry.poker-fate.net"
SERVER_WSS_PORT  = 9012
REAL_SERVER_URI  = f"wss://{SERVER_HOST}:{SERVER_WSS_PORT}"  # overridden at runtime via DNS
EXTERNAL_DNS_SERVERS = [
    "223.5.5.5",   # AliDNS (CN)
    "1.1.1.1",  # Cloudflare
    "4.2.2.1",  # Level 3 / Lumen
    "119.29.29.29",# DNSPod (CN)
    "8.8.8.8",     # Google
]

# ── Local proxy ──────────────────────────────────────────────────────────────
PROXY_HOST   = "0.0.0.0"
WSS_PORT     = 9012

# Additional ports the game might hit on SERVER_HOST → TCP pass-through.
PASSTHROUGH_PORTS: list[int] = [443, 80]

# ── TLS certs (generated by gen_cert.py) ────────────────────────────────────
CERTS_DIR   = Path(__file__).parent / "certs"
CA_CERT     = CERTS_DIR / "ca.crt"
SERVER_CERT = CERTS_DIR / "server.crt"
SERVER_KEY  = CERTS_DIR / "server.key"

# Preferred WSS entry hosts — single source of truth for:
#   gen_cert.py (SAN), proxy.py (preferred host filter), force_domain.py.
# Keep aligned with the login response server list.
PREFERRED_WSS_HOSTS: list[str] = [
    "zga-entry.poker-fate.net",
    "zga-entry.allinmoe.com",
    "ga-foreign.poker-fate.com",
]
CERT_ALT_HOSTS = PREFERRED_WSS_HOSTS  # alias used by gen_cert.py

# ── Bot / game logic ─────────────────────────────────────────────────────────
# MY_SEAT_ID: auto-detected from SitDownRSP — no need to set manually.

# BIG_BLIND / SMALL_BLIND: auto-detected from EnterRoomRSP.
# Set manually here only if auto-detection fails (e.g. reconnect scenario).
BIG_BLIND:   float | None = None   # None = auto-detect
SMALL_BLIND: float | None = None   # None = auto-detect

# ── Watched messages ─────────────────────────────────────────────────────────
WATCH_S2C = {
    # Session setup (auto-detect seat & blinds, track player names)
    "pb.SelfUserInfoRSP",  # learn my uid for reconnect seat re-detection
    "pb.EnterRoomRSP",
    "pb.SitDownRSP",
    "pb.SitDownBRC",    # player name updates when someone sits down
    # Hand lifecycle
    "pb.DealerInfoRSP",
    "pb.HandCardRSP",
    "pb.RoundStartBRC",
    "pb.ActionNotifyBRC",
    "pb.ActionBRC",
    "pb.RoundOverBRC",
    "pb.WinnerRSP",
    "pb.ShowHandRSP",
}

WATCH_C2S = {
    "pb.ActionREQ",
}
