# Interceptor configuration
from pathlib import Path

# ── Real game server ─────────────────────────────────────────────────────────
# Fill in the actual hostname from your mitmproxy capture.
SERVER_HOST      = "zga-entry.poker-fate.net"
SERVER_WSS_PORT  = 9012
REAL_SERVER_URI  = f"wss://{SERVER_HOST}:{SERVER_WSS_PORT}"  # overridden at runtime via DNS
EXTERNAL_DNS_SERVERS = [
    "223.5.5.5",   # AliDNS (CN)
    "1.1.1.1",  # Cloudflare
    "4.2.2.1",  # Level 3 / Lumen
    "119.29.29.29",# DNSPod (CN)
    "8.8.8.8",     # Google
]

# ── Local proxy ──────────────────────────────────────────────────────────────
PROXY_HOST   = "0.0.0.0"
WSS_PORT     = 9012

# Additional ports the game might hit on SERVER_HOST → TCP pass-through.
PASSTHROUGH_PORTS: list[int] = [443, 80]

# ── TLS certs (generated by gen_cert.py) ────────────────────────────────────
CERTS_DIR   = Path(__file__).parent / "certs"
CA_CERT     = CERTS_DIR / "ca.crt"
SERVER_CERT = CERTS_DIR / "server.crt"
SERVER_KEY  = CERTS_DIR / "server.key"

# Preferred WSS entry hosts — single source of truth for:
#   gen_cert.py (SAN), proxy.py (preferred host filter), force_domain.py.
# Keep aligned with the login response server list.
PREFERRED_WSS_HOSTS: list[str] = [
    "zga-entry.poker-fate.net",
    "zga-entry.allinmoe.com",
    "ga-foreign.poker-fate.com",
]
CERT_ALT_HOSTS = PREFERRED_WSS_HOSTS  # alias used by gen_cert.py

# ── Bot / game logic ─────────────────────────────────────────────────────────
# MY_SEAT_ID: auto-detected from SitDownRSP — no need to set manually.

# BIG_BLIND / SMALL_BLIND: auto-detected from EnterRoomRSP.
# Set manually here only if auto-detection fails (e.g. reconnect scenario).
BIG_BLIND:   float | None = None   # None = auto-detect
SMALL_BLIND: float | None = None   # None = auto-detect

# 注入 ActionREQ 前在「客户端已收到轮到自己」之后的等待（秒），上限 3。
# 由 pf_intercept.bot 按 street / 动作 / 底池 随机取值，模拟真人思考时间。
ACTION_INJECT_DELAY_MAX_SEC = 3.0

# 盈利锁仓：一手结束后若桌上筹码 >= 该值（大盲倍数），则记入待离桌；在收到下一手
# pb.DealerInfoRSP（新一手开始）后再发 LeaveRoomREQ，再以 100BB 进房（EnterRoomREQ）。
# 避免 Winner 当下立即离桌与客户端结算界面并发导致 UI 卡住。
# （与客户端菜单一致；StandUpREQ 在客户端里基本未使用，服务端常不处理。）
PROFIT_LOCK_BB_THRESHOLD = 400

# 离桌后等待多久再发 EnterRoomREQ（秒），给客户端切场景/进桌动画一点时间。
PROFIT_LOCK_REENTER_DELAY_SEC = 4.0

# LeaveRoomREQ.seat_reserve：True=留座（降低离桌瞬间座位被他人占走的概率）；若进房异常可改为 False。
PROFIT_LOCK_LEAVE_SEAT_RESERVE = True

# 仅影响发往游戏客户端的 pb.SelfUserInfoRSP 与 pb.EnterRoomRSP（本人座位 player）：本地展示，不改服务器。
# 设为 None 表示不篡改对应字段。EnterRoom 依赖同连接内先收到 SelfUserInfoRSP 以识别 uid。
SPOOF_USER_BRIEF_ROLE_ID: int | None = None
SPOOF_USER_BRIEF_SKIN_ID: int | None = None

# EnterRoom 失败后必发 QuickStartREQ 随机配桌（逻辑在 bot 内固定，与 LobbyByinDialog 一致）。
# 仅当本局从未缓存到 EnterRoomRSP.game_type / EnterRoomRSP.room_info.lobby_coin 时用下列默认：
#   game_type  ← EnumConfig.lua GAME_GAME_TYPE.LOBBY_HOLDEM_GAME (=10010101)，与 pb.EnterRoomRSP.game_type 同源；
#   lobby_coin ← EnumConfig.lua GPropId.Gold (=10100001)，与 pb.RoomInfo.lobby_coin（CSGameDef.proto field 18）及 QuickStartREQ.lobby_coin 一致。
PROFIT_LOCK_FALLBACK_GAME_TYPE = 10010101
PROFIT_LOCK_FALLBACK_LOBBY_COIN = 10100001
# 发 QuickStart 前短暂延迟（秒），给客户端落到大厅状态。
PROFIT_LOCK_QUICKSTART_DELAY_SEC = 0.5

# ── Watched messages ─────────────────────────────────────────────────────────
WATCH_S2C = {
    # Session setup (auto-detect seat & blinds, track player names)
    "pb.SelfUserInfoRSP",  # learn my uid for reconnect seat re-detection
    "pb.EnterRoomRSP",
    "pb.SitDownRSP",
    "pb.SitDownBRC",    # player name updates when someone sits down
    # Hand lifecycle
    "pb.DealerInfoRSP",
    "pb.HandCardRSP",
    "pb.RoundStartBRC",
    "pb.ActionNotifyBRC",
    "pb.ActionBRC",
    "pb.RoundOverBRC",
    "pb.WinnerRSP",
    "pb.ShowHandRSP",
    # Bust-out / rebuy
    "pb.NoticeRebyRSP",  # server notifies us when our chips hit 0 (rebuy window)
    "pb.LeaveRoomRSP",  # profit-lock: after LeaveRoom, inject EnterRoomREQ
}

WATCH_C2S = {
    "pb.ActionREQ",
}
