# Interceptor configuration
from pathlib import Path

# ── Real game server ─────────────────────────────────────────────────────────
# Fill in the actual hostname from your mitmproxy capture.
SERVER_HOST      = "zga-entry.poker-fate.net"
SERVER_WSS_PORT  = 9012
REAL_SERVER_URI  = f"wss://{SERVER_HOST}:{SERVER_WSS_PORT}"  # overridden at runtime via DNS
EXTERNAL_DNS     = "8.8.8.8"   # used to resolve SERVER_HOST, bypassing local hosts file

# ── Local proxy ──────────────────────────────────────────────────────────────
PROXY_HOST   = "0.0.0.0"
WSS_PORT     = 9012

# Additional ports the game might hit on SERVER_HOST → TCP pass-through.
PASSTHROUGH_PORTS: list[int] = []  # disabled for local testing (443/80 require root)

# ── TLS certs (generated by gen_cert.py) ────────────────────────────────────
CERTS_DIR   = Path(__file__).parent / "certs"
CA_CERT     = CERTS_DIR / "ca.crt"
SERVER_CERT = CERTS_DIR / "server.crt"
SERVER_KEY  = CERTS_DIR / "server.key"

# ── Bot / game logic ─────────────────────────────────────────────────────────
# MY_SEAT_ID: auto-detected from SitDownRSP — no need to set manually.

# BIG_BLIND / SMALL_BLIND: auto-detected from EnterRoomRSP.
# Set manually here only if auto-detection fails (e.g. reconnect scenario).
BIG_BLIND:   float | None = None   # None = auto-detect
SMALL_BLIND: float | None = None   # None = auto-detect

# ── Watched messages ─────────────────────────────────────────────────────────
WATCH_S2C = {
    # Session setup (auto-detect seat & blinds, track player names)
    "pb.EnterRoomRSP",
    "pb.SitDownRSP",
    "pb.SitDownBRC",    # player name updates when someone sits down
    # Hand lifecycle
    "pb.DealerInfoRSP",
    "pb.HandCardRSP",
    "pb.RoundStartBRC",
    "pb.ActionNotifyBRC",
    "pb.ActionBRC",
    "pb.RoundOverBRC",
    "pb.WinnerRSP",
    "pb.ShowHandRSP",
}

WATCH_C2S = {
    "pb.ActionREQ",
}
